-- ============================================================================
-- Fase 1 RBAC: Schema replicado do Urânia Hub + seed inicial dos 5 usuários
-- ============================================================================
-- public.users_new:    espelho identitário (id = UUID do Hub; auth_user_id nullable)
-- public.departments:  catálogo hierárquico
-- public.platforms:    catálogo + entry "bi" local
-- public.user_departments, user_platform_access: relacionamentos
-- public.route_access_policies/rules + department_route_access: RBAC runtime
-- public.system_logs, public.tools

-- Nota: users_new vai ser renomeado para users após descomissionar user_profiles.

CREATE TABLE IF NOT EXISTS public.users_new (
  id uuid PRIMARY KEY,
  auth_user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  job_title text,
  is_active boolean NOT NULL DEFAULT true,
  is_global_admin boolean NOT NULL DEFAULT false,
  kommo_user_id integer,
  teams_user_id text,
  phone_whatsapp text,
  notification_preferences jsonb DEFAULT '{"email":true,"whatsapp":false,"teams":false}'::jsonb,
  synced_from_hub_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar NOT NULL UNIQUE,
  name varchar NOT NULL,
  description text,
  parent_department_id integer REFERENCES public.departments(id),
  color varchar,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.platforms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar NOT NULL UNIQUE,
  name varchar NOT NULL,
  description text,
  icon varchar,
  color varchar DEFAULT '#3b82f6',
  base_url text,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  default_role text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users_new(id) ON DELETE CASCADE,
  department_id integer NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
  is_primary boolean DEFAULT false,
  role text NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'leader')),
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, department_id)
);

CREATE TABLE IF NOT EXISTS public.user_platform_access (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users_new(id) ON DELETE CASCADE,
  platform_id integer NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer', 'user', 'manager', 'admin')),
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, platform_id)
);

CREATE TABLE IF NOT EXISTS public.route_access_policies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_id integer NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
  route text NOT NULL,
  label text NOT NULL,
  managed_by text NOT NULL DEFAULT 'global_admin' CHECK (managed_by IN ('global_admin','platform_admin')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(platform_id, route)
);

CREATE TABLE IF NOT EXISTS public.route_access_rules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_id integer NOT NULL REFERENCES public.route_access_policies(id) ON DELETE CASCADE,
  rule_type text NOT NULL CHECK (rule_type IN ('global_admin','platform_admin','department_role','entity_participant','specific_user')),
  platform_id integer REFERENCES public.platforms(id) ON DELETE CASCADE,
  department_id integer REFERENCES public.departments(id) ON DELETE CASCADE,
  min_role text CHECK (min_role IN ('member','leader')),
  user_id uuid REFERENCES public.users_new(id) ON DELETE CASCADE,
  is_system boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.department_route_access (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
  route text NOT NULL,
  label text,
  created_at timestamptz DEFAULT now(),
  UNIQUE(department_id, route)
);

CREATE TABLE IF NOT EXISTS public.system_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  level text NOT NULL CHECK (level IN ('info','warn','error')),
  source text NOT NULL,
  action text NOT NULL,
  actor_id uuid REFERENCES public.users_new(id) ON DELETE SET NULL,
  target_id uuid,
  target_type text,
  metadata jsonb DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_system_logs_created_at ON public.system_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_actor ON public.system_logs(actor_id);

CREATE TABLE IF NOT EXISTS public.tools (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  icon text,
  category text,
  config jsonb DEFAULT '{}'::jsonb,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- RLS + grants
ALTER TABLE public.users_new ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_platform_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_access_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_access_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.department_route_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'users_new','departments','platforms','user_departments','user_platform_access',
    'route_access_policies','route_access_rules','department_route_access','tools'
  ])
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS read_all_authenticated ON public.%I', t);
    EXECUTE format('CREATE POLICY read_all_authenticated ON public.%I FOR SELECT USING (auth.role() = ''authenticated'' OR auth.role() = ''anon'')', t);
    EXECUTE format('GRANT SELECT ON public.%I TO anon, authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
  END LOOP;
END $$;

DROP POLICY IF EXISTS read_system_logs ON public.system_logs;
CREATE POLICY read_system_logs ON public.system_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users_new u WHERE u.auth_user_id = auth.uid() AND u.is_global_admin = true)
);
GRANT SELECT ON public.system_logs TO authenticated;
GRANT ALL ON public.system_logs TO service_role;

-- Helper func
CREATE OR REPLACE FUNCTION public.is_bi_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.users_new u WHERE u.auth_user_id = auth.uid() AND u.is_global_admin = true);
$$;
GRANT EXECUTE ON FUNCTION public.is_bi_admin() TO anon, authenticated, service_role;

-- Trigger handle_new_user adaptado (liga auth.users ao public.users_new por email)
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE existing_id uuid;
BEGIN
  SELECT id INTO existing_id FROM public.users_new WHERE email = NEW.email;
  IF existing_id IS NOT NULL THEN
    UPDATE public.users_new SET auth_user_id = NEW.id, updated_at = now()
    WHERE id = existing_id AND auth_user_id IS DISTINCT FROM NEW.id;
  ELSE
    INSERT INTO public.users_new (id, auth_user_id, email, full_name, is_active)
    VALUES (NEW.id, NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email), true)
    ON CONFLICT (email) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- Índices auxiliares
CREATE INDEX IF NOT EXISTS idx_users_new_auth ON public.users_new(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_users_new_email ON public.users_new(email);
CREATE INDEX IF NOT EXISTS idx_user_departments_user ON public.user_departments(user_id);
CREATE INDEX IF NOT EXISTS idx_user_platform_access_user ON public.user_platform_access(user_id);
CREATE INDEX IF NOT EXISTS idx_route_rules_policy ON public.route_access_rules(policy_id);

-- ============================================================================
-- Seed inicial: plataforma "bi" + 5 usuários atuais preservando permissões
-- ============================================================================

INSERT INTO public.platforms (slug, name, description, icon, color, is_active, display_order)
VALUES ('bi', 'BI Urânia', 'Business Intelligence e Dashboards comerciais/financeiros', 'chart-bar', '#8b5cf6', true, 100)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.users_new (id, auth_user_id, email, full_name, is_active, is_global_admin, synced_from_hub_at)
VALUES
  ('f6b3dc00-9094-4ede-b6c3-fbb8deb1b611', 'c0ea1026-f422-448d-94ba-7ba9077caf85', 'julia.penalva@uraniaplanetario.com.br', 'Julia Penalva', true, true, now()),
  ('53f266e0-eab8-4162-b65a-c384ffe087a8', '8abcecc2-096c-42ad-98cd-49e59c542615', 'raphael@uraniaplanetario.com.br', 'Raphael Galisteo', true, true, now()),
  ('639cb712-292f-49f1-8fdf-265c7aedec35', '62ec3969-412c-4828-8300-e2ab040df2e1', 'leia@uraniaplanetario.com.br', 'Daiana Léia', true, false, now()),
  ('0252872c-f765-4767-b3c2-a0ff8ceac659', '249fe56f-8416-4f80-a534-40347b4906b6', 'marcos.paludo@uraniaplanetario.com.br', 'Marcos Paludo', true, false, now()),
  ('2e24b938-2b30-48be-8d0a-99065dfde18b', '80d38bc7-980d-4cf8-ab7c-940bdb709544', 'sayrana.souto@uraniaplanetario.com.br', 'Sayrana Souto', true, false, now())
ON CONFLICT (email) DO UPDATE SET
  auth_user_id = EXCLUDED.auth_user_id, full_name = EXCLUDED.full_name,
  is_global_admin = EXCLUDED.is_global_admin, synced_from_hub_at = EXCLUDED.synced_from_hub_at,
  updated_at = now();

DO $$
DECLARE bi_id integer;
BEGIN
  SELECT id INTO bi_id FROM public.platforms WHERE slug = 'bi';
  INSERT INTO public.user_platform_access (user_id, platform_id, role) VALUES
    ('f6b3dc00-9094-4ede-b6c3-fbb8deb1b611', bi_id, 'admin'),
    ('53f266e0-eab8-4162-b65a-c384ffe087a8', bi_id, 'admin'),
    ('639cb712-292f-49f1-8fdf-265c7aedec35', bi_id, 'manager'),
    ('0252872c-f765-4767-b3c2-a0ff8ceac659', bi_id, 'manager'),
    ('2e24b938-2b30-48be-8d0a-99065dfde18b', bi_id, 'user')
  ON CONFLICT (user_id, platform_id) DO UPDATE SET role = EXCLUDED.role;
END $$;

-- Policies de rota (sem policy = liberado)
-- Sayrana (role=user) vê só /comercial/qualidade e /comercial/monitoramento.
-- As demais rotas exigem platform_admin (manager/admin) ou global_admin.
DO $$
DECLARE bi_id integer; pol_id integer;
BEGIN
  SELECT id INTO bi_id FROM public.platforms WHERE slug = 'bi';
  FOR pol_id IN
    WITH routes AS (
      SELECT unnest(ARRAY[
        '/comercial/leads-fechados','/comercial/campanhas',
        '/comercial/desempenho-vendedor','/comercial/desempenho-sdr',
        '/financeiro','/admin/usuarios'
      ]) AS route,
      unnest(ARRAY[
        'Leads Fechados','Campanhas Semanais',
        'Desempenho Vendedor','Desempenho SDR',
        'Faturamento','Admin Usuários'
      ]) AS label
    )
    INSERT INTO public.route_access_policies (platform_id, route, label, managed_by)
    SELECT bi_id, route, label, 'global_admin' FROM routes
    ON CONFLICT (platform_id, route) DO UPDATE SET label = EXCLUDED.label
    RETURNING id
  LOOP
    INSERT INTO public.route_access_rules (policy_id, rule_type, is_system) VALUES (pol_id, 'global_admin', true);
    INSERT INTO public.route_access_rules (policy_id, rule_type, platform_id, is_system) VALUES (pol_id, 'platform_admin', bi_id, false);
  END LOOP;
END $$;

-- /admin/usuarios: só global_admin (remover platform_admin que liberaria manager)
DO $$
DECLARE admin_pol_id integer;
BEGIN
  SELECT rap.id INTO admin_pol_id
  FROM public.route_access_policies rap JOIN public.platforms p ON p.id = rap.platform_id
  WHERE p.slug = 'bi' AND rap.route = '/admin/usuarios';
  IF admin_pol_id IS NOT NULL THEN
    DELETE FROM public.route_access_rules
    WHERE policy_id = admin_pol_id AND rule_type = 'platform_admin';
  END IF;
END $$;
